export const USER_LIST_FETCH_SUCCESS = "USER_LIST_FETCH_SUCCESS"
export const USER_LIST_FETCH_LOADING = "USER_LIST_FETCH_LOADING"
export const USER_LIST_FETCH_FAILURE = "USER_LIST_FETCH_FAILURE"

export const USER_DETAIL_FETCH_SUCCESS = "USER_DETAIL_FETCH_SUCCESS"
export const USER_DETAIL_FETCH_LOADING = "USER_DETAIL_FETCH_LOADING"
export const USER_DETAIL_FETCH_FAILURE = "USER_DETAIL_FETCH_FAILURE"

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING"
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE"




